#+TITLE:  Zsh Utilities Modules
#+AUTHOR: Xavier Garrido
#+DATE:   2013-02-16
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:zsh-utilities.org][Zsh Utilities]].

* Zsh Utilities - Modules
This file adds some configuration to external resources. Each program
configuration is done item per item. The preamble is just here to ensure the
binary is present. Thus each item is embedded between a preamble and postamble
block code which is a basic =if= command.

** dotfiles
[[http://pypi.python.org/pypi/dotfiles/][dotfiles]] is a tool to make managing your dotfile symlinks in $HOME easy,
allowing you to keep all your dotfiles in a single directory.
*** Preamble
#+BEGIN_SRC sh
  if (( $+commands[dotfiles] )); then
#+END_SRC

*** Aliases
#+BEGIN_SRC sh :tangle no
  alias dotfiles='dotfiles -R ~/Development/github.com/xgarrido/dotfiles'
#+END_SRC
*** Postamble
#+BEGIN_SRC sh
  fi
#+END_SRC

** fasd
[[https://github.com/clvv/fasd][fasd]] is a command-line productivity booster, offers quick access to files and directories,
inspired by autojump, z and v. Most of the following code is stolen from [[https://github.com/sorin-ionescu/prezto/tree/master/modules/fasd][prezto]].

*** Preamble
#+BEGIN_SRC sh
  if (( $+commands[fasd] )); then
#+END_SRC

*** Initialization
#+BEGIN_SRC sh
  mkdir -p ${HOME}/.config/zsh/tmp
  cache_file="${HOME}/.config/zsh/tmp/fasd_cache.zsh"
  if [[ "${commands[fasd]}" -nt "$cache_file" || ! -s "$cache_file" ]]; then
      # Set the base init arguments.
      init_args=(zsh-hook)

      # Set fasd completion init arguments, if applicable.
      #    if zstyle -t ':prezto:module:completion' loaded; then
      init_args+=(zsh-ccomp zsh-ccomp-install zsh-wcomp zsh-wcomp-install)
      #    fi

      # Cache init code.
      fasd --init "$init_args[@]" >! "$cache_file" 2> /dev/null
  fi
  source "$cache_file"
  unset cache_file init_args
#+END_SRC

*** Additional function for fast =cd=
#+BEGIN_SRC sh
  function fasd_cd {
    local fasd_ret="$(fasd -d "$@")"
    if [[ -d "$fasd_ret" ]]; then
      cd "$fasd_ret"
    else
      print "$fasd_ret"
    fi
  }
#+END_SRC

*** Aliases
**** Change the current working directory interactively
#+BEGIN_SRC sh
  alias j='fasd_cd -i'
#+END_SRC

*** Postamble
#+BEGIN_SRC sh
  fi
#+END_SRC
** rsync
[[http://rsync.samba.org/][rsync]] is an open source utility that provides fast incremental file transfer
*** Preamble
#+BEGIN_SRC sh
  if (( $+commands[rsync] )); then
#+END_SRC

*** Aliases
#+BEGIN_SRC sh
  alias rsync='noglob rsync'
  _rsync_cmd='rsync --verbose --progress --human-readable --compress --archive --hard-links --one-file-system'

  alias rsync-copy="${_rsync_cmd}"
  alias rsync-move="${_rsync_cmd} --remove-source-files"
  alias rsync-update="${_rsync_cmd} --update"
  alias rsync-synchronize="${_rsync_cmd} --update --delete"

  unset _rsync_cmd
#+END_SRC

*** Postamble
#+BEGIN_SRC sh
  fi
#+END_SRC
** colout
[[https://github.com/nojhan/colout][colout]] read lines of text stream on the standard input and output characters
matching a given regular expression /pattern/ in given and /style/: /style/ may
be colored bold strings, for instance.
*** Preamble
#+BEGIN_SRC sh
  if (( $+commands[colout] )); then
#+END_SRC
*** Homemade themes
**** =g++= theme
#+BEGIN_SRC python :tangle colout_myg++.py
  #encoding: utf-8

  def theme():
    import locale
    section="blue"
    # if the locale is unicode
    enc = locale.getpreferredencoding()
    if "UTF" in enc:
      # gcc will use unicode quotes
        qo = "[‘`]"
        qc = "[’']"
    else:
      # rather than ascii ones
        qo = "['`]"
        qc = "'"

    return [
        [ ("error: |erreur: "), "red", "bold" ],
        [ ("warning: |attention: "), "magenta", "bold" ],
        [ ("undefined reference to "), "red", "bold" ],
        # [-Wflag]
        [ "\[-W.*\]", "magenta"],

        # Highlight message start:
        #   path   file   ext     : line   :  col     …
        [ "(/.*?)/([^/:]+): (In .*)",
          section,
          "normal,normal,bold" ],

        [ "(/.*?)/([^/:]+): (At .*)",
          section,
          "normal,normal,bold" ],

        [ ("In file included from"), section ],

        # Highlight locations:
        #   path   file   ext     : line   :  col     …
        [ "(/.*?)/([^/:]+):([0-9]+):*([0-9]*)(.*)",
          "none,magenta,yellow,yellow,none",
          "normal,normal,normal,normal" ],

        # source code in single quotes
        [ qo+"(.*?)"+qc, "green", "bold" ],

        # # source code after a "note: candidate are/is:"
        [ ("note: ")+"((?!.*(candidate|"+qo+"|"+qc+")).*)$", "none", "bold" ],
        # after the code part, to avoid matching ANSI escape chars
        [ ("note: "), "green", "normal" ]
      ]
#+END_SRC

**** =ninja= theme
#+BEGIN_SRC python :tangle colout_ninja.py
  def theme():
      # Ninja theme:
      #  actions building
      building="blue"
      #  actions linking
      linking="green"
      #  actions generating
      generating="blue"

      return [
          # Configure...
          # [ "^--.*works", performed ],
          # [ "^--.*done", performed ],
          # [ "^-- Found.*NO", "red" ],
          # [ "^-- Found.*", performed ],
          # [ "^--.*broken", "red" ],
          # [ "^-- Coult NOT find.*", "red" ],
          # [ "^-- Configuring incomplete, errors occurred!", "red" ],
          # [ "^--.*", performing ],
          # # Errors
          # [ "CMake Error:", "red" ],
          # [ "CMake Warning", "yellow" ],
          # # Scan
          # [ "^(Scanning dependencies of target)(.*)$",
          #   performing, "normal,bold" ],
          # Linking
          [ "\[.*\]\s(Linking .* )(library|executable) (.*/)*(.+(\.[aso]+)*)$",
            linking, "normal,normal,bold" ],
          # Building
          [ "^\[.*\]\s(Building \w* object)(\s+.*/)([-\w]+.c.*)(.o)$",
            "none,none,blue,none", "normal,normal,bold,normal"],
          # [percent] Generating
          [ "^\[.*\]\s(Generating)(\s+.*)$",
            generating, "normal,bold"],
          # # make errors
          # [ "make\[[0-9]+\].*", "yellow"],
          # [ "(make: \*\*\* \[.+\] )(.* [0-9]+)", "red", "normal,bold"],
          # Ninja stop
          [ ".*build stopped.*", "red", "bold" ],
          # progress percentage
          [ "^(\[.*\])", "yellow" ]
      ]
#+END_SRC

**** Logging theme
Theme used to color output from SN@ilWare software. Syntax used is defined in
this file https://nemo.lpc-caen.in2p3.fr/browser/datatools/trunk/include/datatools/logger.h
#+BEGIN_SRC python :tangle colout_mylogging.py
  #encoding: utf-8

  def theme():
      error="red"
      warning="magenta"
      notice="blue"
      debug="green"
      trace="yellow"
      return [
          [ "(^\[error]:|^\[error.*\])(.*$)", error, "bold,normal" ],
          [ "(^\[warning]:|^\[warning.*\])(.*$)", warning, "bold,normal" ],
          [ "(^\[notice]:|^\[notice.*\])(.*$)", notice, "bold,normal" ],
          [ "(^\[debug]:|^\[debug.*\])(.*$)", debug, "bold,normal" ],
          [ "(^\[trace]:|^\[trace.*\])(.*$)", trace, "bold,normal" ],
    ]
#+END_SRC
**** =org-mode= theme

#+BEGIN_SRC python :tangle colout_orgmode.py
  #encoding: utf-8

  def theme():
      return [
          [ "(=[^\"].*?=[^\"])", "cyan" ],
          [ "^\*{1}\s.*$", "red", "bold" ],
          [ "^\*{2}\s.*$", "green", "bold" ],
          [ "^\*{3}\s.*$", "blue", "bold" ],
          [ "^\*{4}\s.*$", "yellow", "bold" ],
          [ "^\*{5}\s.*$", "cyan", "bold" ],
          [ ("((?i)^#\+)(title|date|author|email):(.*)"), "blue", "bold,bold,normal" ],
          [ "#\+.*$", "250" ],
          [ "^:.*:.*$", "250" ],
          [ "\[\w\]", "magenta" ],
          [ "\[\[.*\]\]", "yellow" ],
          [ "^[\||+-].*", "blue" ],
    ]
#+END_SRC

#+RESULTS:

*** Wrapping some functions arround =colout=
**** =cmake=
#+BEGIN_SRC sh
  if (( $+commands[cmake] )); then
      function cmake ()
      {
          $(pkgtools__get_binary_path cmake) $@ | colout -t cmake
      }
  fi
#+END_SRC
**** =ninja=
#+BEGIN_SRC sh
  if (( $+commands[ninja] )); then
      function ninja ()
      {
          $(pkgtools__get_binary_path ninja) $@ | colout -t cmake | colout -t myg++ -T ${zsh_utilities_dir} | colout -t ninja -T ${zsh_utilities_dir}
      }
  fi
#+END_SRC
*** Postamble
#+BEGIN_SRC sh
  fi
#+END_SRC
** mr
*** Preamble
#+BEGIN_SRC sh
  if (( $+commands[mr] )); then
#+END_SRC
*** Function
#+BEGIN_SRC sh
  function mr ()
  {
      last=~/${@[-1]}
      if [ -d $last ]; then
          (
              cd $last
              $(pkgtools__get_binary_path $0) ${@:1:-1}
          )
      else
          $(pkgtools__get_binary_path $0) $@
      fi
  }
#+END_SRC
*** Postamble
#+BEGIN_SRC sh
  fi
#+END_SRC
** plan
[[https://github.com/fengsp/plan][plan]] is a python package for writing and deploying cron jobs. =plan= will convert
python code to cron syntax.
*** Cron syntax
#+BEGIN_SRC python :results output :tangle no
  from plan import Plan

  cron = Plan()

  # cron.command('DISPLAY=:0 /home/garrido/.config/openbox/scripts/change-wallpaper', every='1.hour')
  cron.command('DISPLAY=:0 /home/garrido/Development/org-caldav/sync_calendar.sh', every='1.day', at='12:00')
  cron.command('cp /home/garrido/.emacs.d/tmp/session/emacs.desktop /home/garrido/.emacs.d/tmp/session/emacs-`date +\%Y-\%m-\%d`.desktop', every='monthly')
  cron.command('DISPLAY=:0 /home/garrido/.bin/mybackup --profile lal', every='1.day', at='13:00')
  cron.command('DISPLAY=:0 /home/garrido/.bin/mybackup --profile usb', every='1.day', at='13:00')
  if __name__ == '__main__':
      cron.run('update')
#+END_SRC

#+RESULTS:

** fzf
fzf is a general-purpose command-line fuzzy finder. See
[[https://github.com/junegunn/fzf]]

*** Source file
#+BEGIN_SRC sh
  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
#+END_SRC
*** Preamble
#+BEGIN_SRC sh
  if (( $+commands[fzf] )); then
#+END_SRC
*** Color scheme
#+BEGIN_SRC sh
  export FZF_DEFAULT_OPTS='--color=16,info:4,pointer:3,bg+:15'
#+END_SRC
*** alias
#+BEGIN_SRC sh
  alias f='fzf'
#+END_SRC
*** =fj= - changing directory with fasd
#+BEGIN_SRC sh
  fj() {
      local dir
      dir=$(fasd -Rdl | fzf --no-sort +m) && cd "$dir"
  }
#+END_SRC
*** =fo= - open file
#+BEGIN_SRC sh
  fo() {
      local out file key
      out=$(fzf --query="$1" --exit-0 --expect=ctrl-o,ctrl-e)
      key=$(head -1 <<< "$out")
      file=$(head -2 <<< "$out" | tail -1)
      if [ -n "$file" ]; then
          [ "$key" = ctrl-o ] && xdg-open "$file" || ec "$file"
      fi
  }
#+END_SRC
*** =cdf= - go to the directory where the file is
#+BEGIN_SRC sh
  cdf() {
      local file
      local dir
      file=$(fzf +m -q "$1") && dir=$(dirname "$file") && cd "$dir"
  }
#+END_SRC

*** Postamble
#+BEGIN_SRC sh
  fi
#+END_SRC


# Local Variables:
# firestarter-mode: t
# firestarter: (org-babel-tangle)
# End:
